runtime: nodejs18

handlers:
  - url: /api/.*
    script: auto

env_variables:
  NODE_ENV: production

# Specify the directory where the app server script is located
# In this example, the script is located in cow/app.js
# Modify the path as necessary for your specific app
entrypoint: node nodejs-server/index.js
env_variables:
  PORT: 8080

