name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "master", "main", "delete"]

env:
  PROJECT_ID: backend-382721 # TODO: update Google Cloud project id
  SERVICE: githubactions # TODO: update Cloud Run service name
  REGION: us-east1 # TODO: update Cloud Run service region

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v2
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: PROJECT_ID
          version: master
          credentials: ${{secrets.JSON_CRED}}
          flags: --no-cache
          deliverables: app.yaml

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'