runtime: nodejs18
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: my-react-app/build/\1
  upload: my-react-app/build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: my-react-app/build/index.html
  upload: my-react-app/build/index.html